version: '3'

services:
  web-100:
    container_name: web-100
    build:
      context: ./web
    ports:
      - "8300:80"
    links:
      - php-100
    volumes:
      - ./src/:/var/www/

  php-100:
    container_name: php-100
    build:
      context: ./php
    command: php-fpm -F
    volumes:
      - ./src/:/var/www/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini