version: '3'
services:
  web:
    container_name: web
    build:
      context: ./web
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./app/src:/usr/app/nginx/html

  php:
    container_name: php
    build:
      context: ./php-fpm
    command: php-fpm -F
    volumes:
      - ./app/src:/usr/app/nginx/html